class Variables {
  // translator language Code
  final Map<String, String> lang = {
    "Sindhi": "sd",
    "(Pushto)": "ps",
    "Nepali": "ne",
    "Urdu": "ur",
    "Turkish": "tr",
    "Hindi": "hi",
    "Kashmiri": "ks",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Arabic": "ar",
    "Polska": "pl",
    "New Zealand": "mi",
    "Malta": "mt",
    "Japan": "ja",
    "Italia": "it",
    "Iran": "fa",
    "AUSTRALIA": "au",
    "BAHAMAS": "bs",
    "BAHRAIN": "bh",
    "Telugu": "te",
    "Tamil": "ta",
    "Swedish": "sv",
    "Russian": "ru",
    "Romanian": "ro",
    "Italian": "it",
    "Irish": "ga",
    "Indonesian": "id",
    "Gujarati": "gu",
    "Greek": "el",
    "Farsi": "fa",
    "Breton": "br",
    "Bengali": "bn",
  };
}
